apiVersion: apps/v1
kind: Deployment
metadata:
  name: ga-application
  namespace: rana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rana-ga
  template:
    metadata:
      labels:
        app: rana-ga
    spec:
      containers:
      - name: solar-system
        image: ${{ vars.DOCKER_USERNAME }}/rana-ga:${{ github.sha }}
        ports:
          - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URL
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD
